@startuml

title RT cosmo application (current)

package "OS" {
    component [systemd] as systemd
    component [RLX3 starter] as rlx3starter
    component [Daemonize] as daemonize
    component [RT Cosmo app start.sh] as rtcosmostart
    component [RT Cosmo app binary] as rtcosmoapp
}

systemd -down-> rlx3starter
rlx3starter -down-> daemonize
daemonize -down-> rtcosmostart
rtcosmostart -down-> rtcosmoapp

@enduml
