@startuml

title RT cosmo application control (proposal #2)

package "OS" {
    component [systemd] as systemd
    component [RT Cosmo app binary] as rtcosmoapp
}

systemd -down-> rtcosmoapp

@enduml
